version: '3'
services:
  es01-test:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.15.0'
    networks:
      - default
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
  kib01-test:
    image: 'docker.elastic.co/kibana/kibana:7.15.0'
    networks:
      - default
    environment:
      - ELASTICSEARCH_HOSTS=http://es01-test:9200
    ports:
      - 5601:5601
networks:
  default:
    external: true
    name: elastic
  # nginx:
  #   restart: always
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - '3050:80'
  # app:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./
  #   volumes:
  #     - /app/node_modules
  #     - ./server:/app
